Iter9
zvfkjytytw/humay pull request #11
Opened 2024-06-22 06:57 UTC by zvfkjytytw

Add storage saver

2024-06-28 22:06 UTC, avhitrov requested changes
В общем, все реализовано нормально. Но при асинхронном сохранении возникают гонки (комментарий к коду). Кроме того, при включенном асинхронном сохранении в момент шатдауна сервера вылетает паника по причине повторной попытки закрыть один и тот же канал:
```
panic: close of closed channel

goroutine 7 [running]:
github.com/zvfkjytytw/humay/internal/server/app.(*saver).Stop(0xc000064a20, {0x140900c50?, 0xc0000721e0?})
        C:/work/src/github.com/zvfkjytytw/humay/internal/server/app/saver.go:58 +0x3e
github.com/zvfkjytytw/humay/internal/server/app.(*ServerApp).StopAll(0xc000064a00, {0x140900c50, 0xc0000721e0})
        C:/work/src/github.com/zvfkjytytw/humay/internal/server/app/app.go:111 +0xac
github.com/zvfkjytytw/humay/internal/server/app.(*ServerApp).Run.func1({0x1408fef48, 0xc0000649e0})
        C:/work/src/github.com/zvfkjytytw/humay/internal/server/app/app.go:98 +0x207
created by github.com/zvfkjytytw/humay/internal/server/app.(*ServerApp).Run in goroutine 1
        C:/work/src/github.com/zvfkjytytw/humay/internal/server/app/app.go:94 +0x21c
```
плюс мелкое замечание по использованию switch

2024-06-28 22:06 UTC, avhitrov commented on internal/server/http/middleware/compressor.go
> +				case "gzip":
switch с единственным case - это if. Не следует использовать довольно мощную конструкцию там, где в ней нет необходимости.

2024-06-28 22:06 UTC, avhitrov commented on internal/server/storage/save_restore.go
> +	buf, err := json.Marshal(s)
Вот в этом месте в процессе асинхронного сохранения данных возникают гонки:
```
==================
WARNING: DATA RACE
Read at 0x00c000029a70 by goroutine 9:
  reflect.maplen()
      C:/Apps/Go/src/runtime/map.go:1406 +0x0
  reflect.Value.lenNonSlice()
      C:/Apps/Go/src/reflect/value.go:1785 +0x1e9
  reflect.Value.Len()
      C:/Apps/Go/src/reflect/value.go:1774 +0xf1
  encoding/json.isEmptyValue()
      C:/Apps/Go/src/encoding/json/encode.go:309 +0xe1
  encoding/json.structEncoder.encode()
      C:/Apps/Go/src/encoding/json/encode.go:693 +0x17b
  encoding/json.structEncoder.encode-fm()
      <autogenerated>:1 +0xe4
  encoding/json.ptrEncoder.encode()
      C:/Apps/Go/src/encoding/json/encode.go:876 +0x3f1
  encoding/json.ptrEncoder.encode-fm()
      <autogenerated>:1 +0x84
  encoding/json.(*encodeState).reflectValue()
      C:/Apps/Go/src/encoding/json/encode.go:321 +0x83
  encoding/json.(*encodeState).marshal()
      C:/Apps/Go/src/encoding/json/encode.go:297 +0xea
  encoding/json.Marshal()
      C:/Apps/Go/src/encoding/json/encode.go:163 +0x12b
  github.com/zvfkjytytw/humay/internal/server/storage.(*MemStorage).Save()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/storage/save_restore.go:10 +0x48
  github.com/zvfkjytytw/humay/internal/server/app.(*saver).Start()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/app/saver.go:45 +0x1f8
  github.com/zvfkjytytw/humay/internal/server/app.(*ServerApp).Run.func1()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/app/app.go:95 +0x7a
  github.com/zvfkjytytw/humay/internal/server/app.(*ServerApp).Run.gowrap2()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/app/app.go:101 +0x4f

Previous write at 0x00c000029a70 by goroutine 69:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  github.com/zvfkjytytw/humay/internal/server/storage.(*MemStorage).PutGaugeMetric()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/storage/storage.go:50 +0xec
  github.com/zvfkjytytw/humay/internal/server/http.(*HTTPServer).putJSONValue()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/http/json_metrics.go:107 +0x761
  github.com/zvfkjytytw/humay/internal/server/http.(*HTTPServer).putJSONValue-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/zvfkjytytw/humay/internal/server/http.jsonCtx.func1()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/http/json_metrics.go:70 +0x109b
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/chain.go:31 +0x63
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/zvfkjytytw/humay/internal/server/http.(*HTTPServer).newRouter.Logging.func6.1()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/http/middleware/logging.go:64 +0x272
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5/middleware.Recoverer.func1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/recoverer.go:45 +0xf0
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5/middleware.RequestID.func1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/request_id.go:76 +0x30b
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/zvfkjytytw/humay/internal/server/http.(*HTTPServer).newRouter.Compressor.func5.1()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/http/middleware/compressor.go:49 +0x255
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5/middleware.StripSlashes.func1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/middleware/strip.go:30 +0x275
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Goroutine 9 (running) created at:
  github.com/zvfkjytytw/humay/internal/server/app.(*ServerApp).Run()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/app/app.go:94 +0x21b
  main.main()
      C:/work/src/github.com/zvfkjytytw/humay/cmd/server/main.go:72 +0x684

Goroutine 69 (finished) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  github.com/zvfkjytytw/humay/internal/server/http.(*HTTPServer).Start()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/http/server.go:63 +0xf5
  github.com/zvfkjytytw/humay/internal/server/app.(*ServerApp).Run.func1()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/app/app.go:95 +0x7a
  github.com/zvfkjytytw/humay/internal/server/app.(*ServerApp).Run.gowrap2()
      C:/work/src/github.com/zvfkjytytw/humay/internal/server/app/app.go:101 +0x4f
==================
```

2024-06-29 20:42 UTC, zvfkjytytw commented on internal/server/http/middleware/compressor.go
> +				case "gzip":
Это был вариант для использования разных методов сжатия.
Переделал на if.

2024-06-29 20:44 UTC, zvfkjytytw commented on internal/server/storage/save_restore.go
> +	buf, err := json.Marshal(s)
Добавил лок на время маршаллинга данных. Дальше процесс сохранения работает с внутренним массивом байт и не должен аффектить чтение метрик. Можно ещё на время записи в файл локать, но мне кажется, что это излишне.

2024-07-03 17:21 UTC, zvfkjytytw commented on internal/server/storage/save_restore.go
> +	buf, err := json.Marshal(s)
Передвинул синхронную запись в файл в первый defer, чтобы не столкнуться с локом при сохранении метрики.

2024-07-03 17:25 UTC, zvfkjytytw commented on internal/server/http/middleware/compressor.go
> +				case "gzip":
поместил закрытие канала в сейвере в once.Do

2024-07-04 22:28 UTC, avhitrov approved these changes
Все замечания учтены. Аппрув!

2024-07-05 04:13 UTC, merged