Iter5
zvfkjytytw/humay pull request #7
Opened 2024-05-20 12:14 UTC by zvfkjytytw

Read Env variables

2024-05-23 23:17 UTC, avhitrov requested changes
1. Неверно реализован счетчик
2. На сервере не реализован хендлер выдачи всех параметров (GET /)
3. Потенциальные гонки в сторадже
4. Прочие замечания в комментариях к коду

2024-05-23 23:17 UTC, avhitrov commented on internal/agent/metrics/poller.go
> +	p.Metrics.Counter["PollCount"] = int64(len(p.Metrics.Gauge))
Счетчик должен считать не количество снятых метрик, а количество проходов по снятию метрик. Буквально в задании:
```
счётчик, увеличивающийся на 1 при каждом обновлении метрики из пакета runtime (на каждый pollInterval — см. ниже)
```
Можно, наверное, трактовать и так, что на каждую метрику увеличивать счетчик, но он в любом случае должен инкрементиться, и его итоговое значение должно отправляться на сервер. И сбрасываться в случае успешной отправки.

В общем, идеальным решением считаю (при текущих параметрах 2 и 10) увеличение на сервере значения счетчика на 5 каждые 10 секунд.

2024-05-23 23:17 UTC, avhitrov commented on internal/server/app/app.go
> +	wg.Add(len(a.services))
WaitGroup нужна для слежения и синхронизации горутин. В данном случае ее использование лишено смысла. Стандартный паттерн: перед открытием горутины инкрементим wg, пробрасываем внутрь (или через захват переменной организуем) и внутри выполняем wg.Done() в конце функции, которая декрементит счетчик группы. В каком-то месте ставим wg.Wait(), в этом месте будем ждать окончания работы всех запущенных горутин.

2024-05-23 23:17 UTC, avhitrov commented on internal/server/http/router.go
> +	r.Get("/*", notImplementedYet)
В соответствии с заданием 3 итерации должно быть имплементировано:
```
По запросу GET http://<АДРЕС_СЕРВЕРА>/ сервер должен отдавать HTML-страницу со списком имён и значений всех известных ему на текущий момент метрик.
```

2024-05-23 23:17 UTC, avhitrov commented on internal/server/storage/storage.go
> +	vector map[int64]int64
Учитывая то, что при каждом сохранении значения в MemStorage вся структура переписывается заново, не вижу какого-то специального смысла делать здесь мапу. В ней всегда строго одно значение.

2024-05-23 23:17 UTC, avhitrov commented on internal/server/storage/storage.go
> +	counterMetrics map[string]*counterMetric
Мапа – структура потоконебезопасная. Это означает, что в конкурентной среде (а http-сервер априори является конкурентным приложением, так как открывает по горутине на каждый входящий запрос) любые обращения к ней должны оборачиваться блокировками. В Go для этого существуют мьютексы (sync.Mutex или sync.RWMutex). Кроме того, можно использовать потокозащищенные структуры, вроде sync.Map.

Подробнее: https://t.me/bushigo/24

2024-05-26 16:27 UTC, zvfkjytytw commented on internal/server/storage/storage.go
> +	counterMetrics map[string]*counterMetric
Добавил мьютексы.

2024-05-26 16:31 UTC, zvfkjytytw commented on internal/server/storage/storage.go
> +	vector map[int64]int64
Переписываться заново (или инкрементироваться) должно поле value. В vector записываю соответствие полученной метрики ко времени получения. Есть идея сделать выдачу vector в отдельной ручке и хранить в нем значения за последний час (условно), тогда можно в web интерфейсе сделать отображение графика по метрике.

2024-05-26 16:32 UTC, zvfkjytytw commented on internal/server/http/router.go
> +	r.Get("/*", notImplementedYet)
Добавил страницу в metricspage.go

2024-05-26 16:35 UTC, zvfkjytytw commented on internal/server/app/app.go
> +	wg.Add(len(a.services))
Убрал WaitGroup. Мне казалось, что поскольку сервисы (наверное grpc тоже надо будет добавлять) я запускаю в горутинах, то при остановке нужно дождаться выполнения всех Stop функций. Может быть и Stop функции  запускать в отдельных горутинах.

2024-05-26 16:35 UTC, zvfkjytytw commented on internal/agent/metrics/poller.go
> +	p.Metrics.Counter["PollCount"] = int64(len(p.Metrics.Gauge))
Исправил

2024-06-01 20:08 UTC, avhitrov commented on internal/server/app/app.go
> +	wg.Add(len(a.services))
Когда будем прорабатывать graceful shutdown, проговорим это.

2024-06-01 20:12 UTC, avhitrov commented on internal/server/storage/storage.go
> +	vector map[int64]int64
Этого нет в задании. Этого не будет в развитии задания. Не буду заострять на этом внимание сейчас, но в следующих итерациях все равно придется отрефакторить, так как дальнейшее развитие сервиса пойдет в другую сторону.

2024-06-01 20:17 UTC, avhitrov requested changes
Почти все хорошо, но блокировки не на месте.

2024-06-01 20:17 UTC, avhitrov commented on internal/server/storage/storage.go
> +	metric, ok := s.gaugeMetrics[name]
Гонки будут возникать в момент конкурентного чтения записи данной мапы. Блокировку ставить надо ДО, а не после. И закрывать уже после закрытия функции (то есть, весь блок lock - defer unlock) должен находиться в начале функции. Предлагаю еще раз внимательно перечитать пост в телеге.

2024-06-04 06:02 UTC, zvfkjytytw commented on internal/server/storage/storage.go
> +	vector map[int64]int64
переделал

2024-06-04 06:03 UTC, zvfkjytytw commented on internal/server/storage/storage.go
> +	counterMetrics map[string]*counterMetric
поставил мьютексы на основную структуру в начале методов

2024-06-04 11:12 UTC, zvfkjytytw commented on internal/server/storage/storage.go
> +	metric, ok := s.gaugeMetrics[name]
поставил мьютексы на основную структуру в начале методов

2024-06-08 21:51 UTC, avhitrov approved these changes
Все отлично!

2024-06-11 06:52 UTC, merged